version: "3.7"
name: loaner-dev

services:
  python:
    container_name: loaner-python
    build:
      context: ./../api
      dockerfile: ../docker/dev/python/Dockerfile.dev
    command: gunicorn --bind 0.0.0.0:5000 cli:app
    volumes:
      - ../api:/usr/src/app
    expose:
      - 5000
    env_file:
      - ../api/.env.dev
    networks:
      - loaner-internal
    depends_on:
      - redis

  nginx:
    image: nginx:alpine
    container_name: loaner-nginx
    restart: unless-stopped
    ports:
      - 1337:80
    volumes:
      - ./../api:/app
      - ./../docker/dev/nginx:/etc/nginx/conf.d
    networks:
      - loaner-external
      - loaner-internal
    depends_on:
      - python

  node:
    image: node:lts-bullseye
    container_name: loaner-vue
    environment:
      NODE_ENV: dev
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - ./../frontend:/usr/app
    working_dir: /usr/app
    entrypoint: >
      bash -c "npm install && npm run dev"
    networks:
      - loaner-external
    depends_on:
      - python

  redis:
    container_name: loaner-redis
    image: "redis:alpine"
    ports:
      - 6379:6379
    volumes:
      - "loaner-redis:/data"
    networks:
      - loaner-internal
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s

  redisinsight:
    image: "redislabs/redisinsight:latest"
    container_name: loaner-redisinsight
    ports:
      - 8001:8001
    volumes:
      - "loaner-redisinsight:/db"
    networks:
      - loaner-internal
      - loaner-external
    restart: always
    depends_on:
      - redis

networks:
  loaner-internal:
    driver: bridge
  loaner-external:
    driver: bridge

volumes:
  loaner-redis:
    driver: local
  loaner-redisinsight:
    driver: local
